//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.SalesItems = new HashSet<SalesItem>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ItemCategoryId { get; set; }
    
        public virtual ICollection<SalesItem> SalesItems { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
