//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHeader
    {
        public SalesHeader()
        {
            this.SalesItems = new HashSet<SalesItem>();
        }
    
        public int SalesId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> OrderSalesBalance { get; set; }
        public Nullable<decimal> OrderTaxAmount { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public string SalesStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SalesItem> SalesItems { get; set; }
    }
}
